import type { NextPage } from 'next';
import Head from 'next/head';
import Image from 'next/image';
import Link from 'next/link';
import BodyLayout from './content/BodyLayout';
import EndLayout from './content/EndLayout';
import MainLayout from './content/MainLayout';

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <MainLayout />
      <BodyLayout/>
      <EndLayout/>
    </div>
  );
};

export default Home;
