import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import { useAppDispatch, useAppSelector } from "../redux/hooks";
import { addLineItem } from "../redux/features/cartSlice";
import { LineItemType } from "../interfaces";
import { Fragment } from "react";

const Home: NextPage = () => {
    const count = useAppSelector((state) => state.cart)
    const dispatch = useAppDispatch()

        const cart: LineItemType = {
        product_id: "2323",
        productName: "",
        productDescription: "",
        productPrice: 0,
        productImage: "",
        productCategory: "",
        productQuantity: 0,
        productSeller: "",
        productStatus: "",
        productBrand: ""

    }
    const add = () => {
        dispatch(addLineItem(cart))
    }
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Link href="./auth/AdminLogin">admin login</Link>

        <button className="px-12 py-4 bg-red-500 text-white font-bold" onClick={() => add()}>add to cart</button>
    </div>
  );
};

export default Home;
